sudo: false
language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - docker-compose up -d

script:
  - npm run lint
  - npm run test
  - npm run cucumber:docker

after_success:
  - npm run codecov
